name: "Build and deploy"
on:
  push:
  pull_request:
jobs:
  stable:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      if: "github.ref == 'refs/heads/master'"
      env:
        CLOUD_TOKEN: ${{ secrets.CLOUD_TOKEN }}
      run: "./ci/build.sh stable"
    - name: Build
      if: "github.ref != 'refs/heads/master'"
      run: "./ci/build.sh stable"
  nixos_22_11:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      if: "github.ref == 'refs/heads/master'"
      env:
        CLOUD_TOKEN: ${{ secrets.CLOUD_TOKEN }}
      run: "./ci/build.sh 22.11"
    - name: Build
      if: "github.ref != 'refs/heads/master'"
      run: "./ci/build.sh 22.11"
  nixos_22_05:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      if: "github.ref == 'refs/heads/master'"
      env:
        CLOUD_TOKEN: ${{ secrets.CLOUD_TOKEN }}
      run: "./ci/build.sh 22.05"
    - name: Build
      if: "github.ref != 'refs/heads/master'"
      run: "./ci/build.sh 22.05"
  nixos_21_11:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      if: "github.ref == 'refs/heads/master'"
      env:
        CLOUD_TOKEN: ${{ secrets.CLOUD_TOKEN }}
      run: "./ci/build.sh 21.11"
    - name: Build
      if: "github.ref != 'refs/heads/master'"
      run: "./ci/build.sh 21.11"
