name: "Build and deploy"
on:
  push:
  pull_request:
jobs:
  stable:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      if: "github.ref == 'refs/heads/master'"
      env:
        CLOUD_TOKEN: ${{ secrets.CLOUD_TOKEN }}
      run: "./ci/build.sh stable"
    - name: Build
      if: "github.ref != 'refs/heads/master'"
      run: "./ci/build.sh stable"
  nixos_20_09:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      if: "github.ref == 'refs/heads/master'"
      env:
        CLOUD_TOKEN: ${{ secrets.CLOUD_TOKEN }}
      run: "./ci/build.sh 20.09"
    - name: Build
      if: "github.ref != 'refs/heads/master'"
      run: "./ci/build.sh 20.09"
  nixos_20_03:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      if: "github.ref == 'refs/heads/master'"
      env:
        CLOUD_TOKEN: ${{ secrets.CLOUD_TOKEN }}
      run: "./ci/build.sh 20.03"
    - name: Build
      if: "github.ref != 'refs/heads/master'"
      run: "./ci/build.sh 20.03"
  nixos_21_05:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      if: "github.ref == 'refs/heads/master'"
      env:
        CLOUD_TOKEN: ${{ secrets.CLOUD_TOKEN }}
      run: "./ci/build.sh 21.05"
    - name: Build
      if: "github.ref != 'refs/heads/master'"
      run: "./ci/build.sh 21.05"
